//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.4-10/27/2009 06:09 PM(mockbuild)-fcs
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2009.12.23 at 06:27:19 PM PST
//

package com.github.sardine.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;any/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "href", "property", "all", "authenticated", "unauthenticated", "self" })
@XmlRootElement(name = "principal")
public class Principal {

	private String href;
	private Property property;
	private All all;
	private Authenticated authenticated;
	private Unauthenticated unauthenticated;
	private Self self;

	public All getAll() {
		return this.all;
	}

	public Authenticated getAuthenticated() {
		return this.authenticated;
	}

	public String getHref() {
		return this.href;
	}

	public Property getProperty() {
		return this.property;
	}

	public Self getSelf() {
		return this.self;
	}

	public Unauthenticated getUnauthenticated() {
		return this.unauthenticated;
	}

	public void setAll(final All all) {
		this.all = all;
	}

	public void setAuthenticated(final Authenticated authenticated) {
		this.authenticated = authenticated;
	}

	public void setHref(final String href) {
		this.href = href;
	}

	public void setProperty(final Property property) {
		this.property = property;
	}

	public void setSelf(final Self self) {
		this.self = self;
	}

	public void setUnauthenticated(final Unauthenticated unauthenticated) {
		this.unauthenticated = unauthenticated;
	}

}
